# Generated by Django 2.2.4 on 2020-08-04 14:53

from django.db import migrations
import phonenumbers


def normalize_phones(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owners_phonenumber_pure = phonenumbers.parse(flat.owners_phonenumber, "RU")
        if phonenumbers.is_valid_number(flat.owners_phonenumber_pure):
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owners_phonenumber_pure'),
    ]

    operations = [
        migrations.RunPython(normalize_phones),
    ]
