# Generated by Django 2.2.4 on 2020-08-04 16:25

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20200804_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='full_name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='ФИО владельца'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owners_phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=20, region=None, verbose_name='Номер владельца'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owners_phonenumber_pure',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=20, region=None, verbose_name='Нормализованный номер владельца'),
        ),
    ]
