# Generated by Django 2.2.4 on 2020-08-04 16:25

from django.db import migrations


def create_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner, created = Owner.objects.get_or_create(full_name=flat.owner, owners_phonenumber=flat.owners_phonenumber,
                                                     defaults={
                                                         'owners_phonenumber_pure': flat.owners_phonenumber_pure,
                                                     })
        owner.flats.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20200804_1925'),
    ]

    operations = [
        migrations.RunPython(create_owners),
    ]
